language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
    - pip install -r redsample/test/requirements.txt
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install robotframework-python3
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install robotframework-python3
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install robotframework-python3; else pip install robotframework; fi
script:
    - nosetests --with-coverage --cover-erase --cover-package=redsample
    - pybot redsample/test/*.robot
after_success:
    - coveralls
